flowchart LR
subgraph plan["Planning: het recept"]
    
    subgraph 01_smelten["Smelt chocolade en boter + homogeniseer"]
        01.1_boter_en_chocolade_in_pan["Boter en chocolade in pan"]
        style 01.1_boter_en_chocolade_in_pan color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        01.2_verwarm_pan["Verwarm de pan op het vuur"]
        style 01.2_verwarm_pan color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        01.3_roer_tot_homogeen_vloeibaar_mengsel["Roer tot homogeen mengsel"]
        style 01.3_roer_tot_homogeen_vloeibaar_mengsel color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style 01_smelten color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff

    subgraph 02_hak_noten["Hak walnoten"]
        02.1_hak_noten["Hak de walnoten fijn"]
        style 02.1_hak_noten color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style 02_hak_noten color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff

    subgraph 03_mengen["Maak beslag"]
        03.1_eieren_en_suiker_in_kom["Eieren en suiker in een kom"]
        style 03.1_eieren_en_suiker_in_kom color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        03.2_klop_tot_homogeen_mengsel["Klop eieren en suiker tot een homogeen mengsel"]
        style 03.2_klop_tot_homogeen_mengsel color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        03.3_chocolade_toevoegen["Voeg chocolade toe"]
        style 03.3_chocolade_toevoegen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        03.4_voeg_noten_toe["Voeg gehakte walnoten toe"]
        style 03.4_voeg_noten_toe color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        03.5_bloem_toevoegen["Voeg bloem toe"]
        style 03.5_bloem_toevoegen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        03.6_beslag_kloppen["Klop alles tot een homogeen beslag"]
        style 03.6_beslag_kloppen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style 03_mengen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff

    subgraph 04_bakken["Bak het beslag"]
        04.1_voorverwarmen["Verwarm de oven tot 180 graden"]
        style 04.1_voorverwarmen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        04.2_beslag_in_bakvorm["Vul de bakvorm met beslag"]
        style 04.2_beslag_in_bakvorm color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        04.3_bakvorm_in_oven["Plaats de bakvorm in de oven"]
        style 04.3_bakvorm_in_oven color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        04.4_laat_bakken_tot_lichtbruine_bovenkant["Laat ongeveer 25 minuten bakken tot de bovenzijde bleekbruin is"]
        style 04.4_laat_bakken_tot_lichtbruine_bovenkant color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style 04_bakken color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    subgraph 05_slot["Afkoelen en snijden"]
        05.1_afkoelen["Laat de brownies afkoelen"]
        style 05.1_afkoelen color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        05.2_snijden["Snijd in maximaal 48 stukken"]
        style 05.2_snijden color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style 05_slot color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff


    01_smelten --> 02_hak_noten
    01.1_boter_en_chocolade_in_pan --> 01.2_verwarm_pan
    01.2_verwarm_pan --> 01.3_roer_tot_homogeen_vloeibaar_mengsel
    02_hak_noten -->  03_mengen
    03.1_eieren_en_suiker_in_kom --> 03.2_klop_tot_homogeen_mengsel
    03.2_klop_tot_homogeen_mengsel--> 03.3_chocolade_toevoegen
    03.3_chocolade_toevoegen --> 03.4_voeg_noten_toe
    03.4_voeg_noten_toe --> 03.5_bloem_toevoegen
    03.5_bloem_toevoegen --> 03.6_beslag_kloppen
    03_mengen --> 04_bakken
    04.1_voorverwarmen--> 04.2_beslag_in_bakvorm
    04.2_beslag_in_bakvorm--> 04.3_bakvorm_in_oven
    04.3_bakvorm_in_oven--> 04.4_laat_bakken_tot_lichtbruine_bovenkant
    04_bakken --> 05_slot




    bloem(["Bloem"])
    style bloem color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    bloem -.->|225 gr| 03.5_bloem_toevoegen

    boter(["Boter"])
    style boter color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    boter -.->|375 gr| 01.1_boter_en_chocolade_in_pan

    donkere-chocolade(["Donkere chocolade"])
    style donkere-chocolade color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    donkere-chocolade -.->|375 gr| 01.1_boter_en_chocolade_in_pan

    suiker(["kristalsuiker"])
    style suiker color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    suiker -.->|500 gr| 03.1_eieren_en_suiker_in_kom

    eieren(["Eieren"])
    style eieren color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    eieren -.->|6 stuks| 03.1_eieren_en_suiker_in_kom

    gesmolten_mengsel(["Gesmolten boter-chocolade"])
    style gesmolten_mengsel color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    gesmolten_mengsel -.->  03.3_chocolade_toevoegen
    01.3_roer_tot_homogeen_vloeibaar_mengsel -.-> gesmolten_mengsel

    walnoten(["Walnoten"])
    style walnoten color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    walnoten -.->|300 gr| 02.1_hak_noten

    gehakte_walnoten(["Gehakte walnoten"])
    style gehakte_walnoten color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    02.1_hak_noten -.-> gehakte_walnoten
    gehakte_walnoten -.-> 03.4_voeg_noten_toe

    beslag(["Browniebeslag"])
    style beslag color:white,fill:#FF9500,stroke:#CC7700,color:#fff
    03.6_beslag_kloppen -.-> beslag
    beslag -.-> 04.2_beslag_in_bakvorm

    kleur(["Bleekbruine bovenkant"])
    style kleur color:white,fill:#7ED321,stroke:#5A9E17,color:#fff
    04.4_laat_bakken_tot_lichtbruine_bovenkant -.-> kleur
    kleur -.-> 05.1_afkoelen
    
end

subgraph deployment["Deployment: de systeemconfiguratie op een bepaald platform (mijn keuken)"]

    subgraph smeltsysteem["Het systeem in de keuken dat mengsels homogeen vloeibaar kan maken"]
        pan["Gietijzeren pan"]
        style pan color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        pan -.->|implementeert| 01.1_boter_en_chocolade_in_pan
        garde["Garde"]
        style garde color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        garde -.->|implementeert| 01.3_roer_tot_homogeen_vloeibaar_mengsel
        gasvuur["Gasvuur"]
        style gasvuur color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        gasvuur -.->|implementeert| 01.2_verwarm_pan
    end
    style smeltsysteem color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    subgraph haksysteem["Het systeem in de keuken dat nootjes kan hakken"]
        snijplank["Snijplank van Geert"]
        style snijplank color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        mes["Mes"]
        style mes color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style haksysteem color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    haksysteem -.->|implementeert| 02_hak_noten
    subgraph keukenrobot["Het systeem in de keuken dat alles mengt"]
        Keukenrobot["Keukenrobot van Geert"]
        style Keukenrobot color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style keukenrobot color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    keukenrobot -.->|implementeert| 03_mengen
    subgraph baksysteem["Het systeem in de keuken dat bakt"]
        bakvorm["De grote aluminium bakvorm van Geert"]
        style bakvorm color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
        oven["Oven van Geert"]
        style oven color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    end
    style baksysteem color:white,fill:#4A90E2,stroke:#2E5C8A,color:#fff
    baksysteem -.->|implementeert| 04_bakken

    pan --- gasvuur
    gasvuur --- garde
    garde --- snijplank
    snijplank --- mes
    mes --- Keukenrobot
    Keukenrobot --- bakvorm
    bakvorm --- oven

end

    deployment -.->|implementeert| plan









