flowchart RL

%% =====================================================
%% PLANNING
%% =====================================================
    subgraph PLANNING["PLANNING"]
        PLAN0([Plan: Nigella Brownies])

        STEP_smelt([Step: Smelten])
        STEP_hak([Step: Hakken])
        STEP_meng([Step: Mengen])
        STEP_bak([Step: Bakken])
        STEP_afkoelen([Step: Afkoelen])
        PLAN_BAK["Bakken"]

        STEP_controle([Step: Kwaliteitscontrole])

        PLAN_SMELT["Smelten"]

        V_boter([var:boter])
        V_choc([var:donkere-chocolade])
        V_walnoten([var:walnoten])
        V_suiker([var:suiker])
        V_eieren([var:eieren])
        V_bloem([var:bloem])
        V_smelt([var:gesmolten-mengsel])
        V_hak([var:gehakte-walnoten])
        V_beslag([var:beslag])
        V_brownies([var:brownies])
        V_kleur([var:kleur])

    end




    style PLANNING fill:#b8a2d4,stroke:#2E5C8A,color:#000
    style PLAN0 fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_smelt fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_hak fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_meng fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_bak fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_afkoelen fill:#7f59ae,stroke:#2E5C8A,color:#000
    style STEP_controle fill:#7f59ae,stroke:#2E5C8A,color:#000
    style PLAN_SMELT fill:#c6a0f5,stroke:#2E5C8A,color:#000
    style PLAN_BAK fill:#c6a0f5,stroke:#2E5C8A,color:#000

    style V_boter fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_choc fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_walnoten fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_suiker fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_eieren fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_bloem fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_smelt fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_hak fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_beslag fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_brownies fill:#fe7130,stroke:#2E5C8A,color:#000
    style V_kleur fill:#fe7130,stroke:#2E5C8A,color:#000

%% Plan structuur
    PLAN0 -->|hasStep| STEP_smelt
    PLAN0 -->|hasStep| STEP_hak
    PLAN0 -->|hasStep| STEP_meng
    PLAN0 -->|hasStep| STEP_bak
    PLAN0 -->|hasStep| STEP_afkoelen
    PLAN0 -->|hasStep| STEP_controle

    PLAN0 -->|hasSubPlan| PLAN_SMELT
    PLAN0 -->|hasSubPlan| PLAN_BAK


    STEP_smelt -->|isDecomposedAsPlan| PLAN_SMELT
    STEP_bak -->|isDecomposedAsPlan| PLAN_BAK

    STEP_afkoelen -.->|isPrecededBy| STEP_controle -.->|isPrecededBy| STEP_bak -.->|isPrecededBy| STEP_meng -.->|isPrecededBy| STEP_hak -.->|isPrecededBy| STEP_smelt


%% Variabelen
    V_boter -->|isInputVarOf| STEP_smelt
    V_choc -->|isInputVarOf| STEP_smelt
    V_smelt -->|isOutputVarOf| STEP_smelt

    V_walnoten -->|isInputVarOf| STEP_hak
    V_hak -->|isOutputVarOf| STEP_hak

    V_smelt -->|isInputVarOf| STEP_meng
    V_hak -->|isInputVarOf| STEP_meng
    V_suiker -->|isInputVarOf| STEP_meng
    V_eieren -->|isInputVarOf| STEP_meng
    V_bloem -->|isInputVarOf| STEP_meng
    V_beslag -->|isOutputVarOf| STEP_meng

    V_beslag -->|isInputVarOf| STEP_bak
    V_brownies -->|isOutputVarOf| STEP_bak
    V_kleur -->|isOutputVarOf| STEP_controle
    V_kleur -->|isInputVarOf| STEP_afkoelen
    V_brownies -->|isInputVarOf| STEP_afkoelen
    V_brownies -->|isOutputVarOf| STEP_afkoelen



%% =====================================================
%% DEPLOYMENT
%% =====================================================
    subgraph DEPLOYMENT["DEPLOYMENT"]
        Platform([Platform: Keuken])
        Deployment([Deployment])

        SYS_smelt([System: Smeltsysteem])
        SYS_hak([System: Haksysteem])
        SYS_robot([System: Keukenrobot])
        SYS_oven([System: Oven])
        SYS_Sensor([System: Sensor])
    end

    style DEPLOYMENT fill:#b0d9e7,stroke:#2E5C8A,color:#000
    style Platform fill:#60c4e4,stroke:#2E5C8A,color:#000
    style Deployment fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS_smelt fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS_hak fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS_Sensor fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS_robot fill:#60c4e4,stroke:#2E5C8A,color:#000
    style SYS_oven fill:#60c4e4,stroke:#2E5C8A,color:#000

    Deployment -->|deployedOnPlatform| Platform
    Deployment -->|deployedAsset| SYS_smelt
    Deployment -->|deployedAsset| SYS_hak
    Deployment -->|deployedAsset| SYS_robot
    Deployment -->|deployedAsset| SYS_oven
    Deployment -->|deployedAsset| SYS_Sensor

    SYS_smelt -->|implements| STEP_smelt
    SYS_hak -->|implements| STEP_hak
    SYS_robot -->|implements| STEP_meng
    SYS_oven -->|implements| STEP_bak
    SYS_Sensor -->|implements| STEP_controle


%% =====================================================
%% EXECUTION
%% =====================================================
    subgraph EXECUTION["EXECUTION — 10 Feb 2026"]

        Activity_smelt([Activity: Smelten])
        Activity_hak([Activity: Hakken])
        Activity_meng([Activity: Mengen])
        Activity_bak([Activity: Bakken])
        Activity_obs([Observation: Kleur])

        subgraph DERIVATION["DERIVATION — 10 Feb 2026"]
            I_boter([Entity: Boter])
            I_choc([Entity: Chocolade])
            I_wal([Entity: Walnoten])
            I_suiker([Entity: Suiker])
            I_eieren([Entity: Eieren])
            I_bloem([Entity: Bloem])
            T_smelt([Entity: Gesmolten mengsel])
            T_hak([Entity: Gehakte walnoten])
            T_beslag([Entity: Beslag])
            R_brownies([Entity: Brownies])
            O_kleur([Entity: Lichtbruine kleur])
        end
    end

    style DERIVATION fill:#f8e1ad,stroke:#2E5C8A,color:#000
    style EXECUTION fill:#e7a3be,stroke:#2E5C8A,color:#000
    style Activity_smelt fill:#e54b89,stroke:#2E5C8A,color:#000
    style Activity_hak fill:#e54b89,stroke:#2E5C8A,color:#000
    style Activity_meng fill:#e54b89,stroke:#2E5C8A,color:#000
    style Activity_bak fill:#e54b89,stroke:#2E5C8A,color:#000
    style Activity_obs fill:#e54b89,stroke:#2E5C8A,color:#000

    style I_boter fill:#f8b622,stroke:#2E5C8A,color:#000
    style I_choc fill:#f8b622,stroke:#2E5C8A,color:#000
    style I_wal fill:#f8b622,stroke:#2E5C8A,color:#000
    style I_suiker fill:#f8b622,stroke:#2E5C8A,color:#000
    style I_eieren fill:#f8b622,stroke:#2E5C8A,color:#000
    style I_bloem fill:#f8b622,stroke:#2E5C8A,color:#000
    style T_smelt fill:#f8b622,stroke:#2E5C8A,color:#000
    style T_hak fill:#f8b622,stroke:#2E5C8A,color:#000
    style T_beslag fill:#f8b622,stroke:#2E5C8A,color:#000
    style R_brownies fill:#f8b622,stroke:#2E5C8A,color:#000
    style O_kleur fill:#f8b622,stroke:#2E5C8A,color:#000

%% Activity relaties
    Activity_smelt -->|correspondsToStep| STEP_smelt
    Activity_hak -->|correspondsToStep| STEP_hak
    Activity_meng -->|correspondsToStep| STEP_meng
    Activity_bak -->|correspondsToStep| STEP_bak

    Activity_smelt -->|madeBySystem| SYS_smelt
    Activity_hak -->|madeBySystem| SYS_hak
    Activity_meng -->|madeBySystem| SYS_robot
    Activity_bak -->|madeBySystem| SYS_oven

    Activity_smelt -->|used| I_boter
    Activity_smelt -->|used| I_choc
    Activity_smelt -->|hasResult| T_smelt

    Activity_hak -->|used| I_wal
    Activity_hak -->|hasResult| T_hak

    Activity_meng -->|used| T_smelt
    Activity_meng -->|used| T_hak
    Activity_meng -->|used| I_suiker
    Activity_meng -->|used| I_eieren
    Activity_meng -->|used| I_bloem
    Activity_meng -->|hasResult| T_beslag

    Activity_bak -->|used| T_beslag
    Activity_bak -->|hasResult| R_brownies

    Activity_obs -->|hasResult| O_kleur

%% Derivatie
    T_smelt -->|wasDerivedFrom| I_boter
    T_smelt -->|wasDerivedFrom| I_choc
    T_hak -->|wasDerivedFrom| I_wal
    T_beslag -->|wasDerivedFrom| T_smelt
    T_beslag -->|wasDerivedFrom| T_hak
    T_beslag -->|wasDerivedFrom| I_suiker
    T_beslag -->|wasDerivedFrom| I_eieren
    T_beslag -->|wasDerivedFrom| I_bloem
    R_brownies -->|wasDerivedFrom| T_beslag

%% Entity ↔ Variable
    I_boter -->|correspondsToVariable| V_boter
    I_choc -->|correspondsToVariable| V_choc
    I_wal -->|correspondsToVariable| V_walnoten
    I_suiker -->|correspondsToVariable| V_suiker
    I_eieren -->|correspondsToVariable| V_eieren
    I_bloem -->|correspondsToVariable| V_bloem
    T_smelt -->|correspondsToVariable| V_smelt
    T_hak -->|correspondsToVariable| V_hak
    T_beslag -->|correspondsToVariable| V_beslag
    R_brownies -->|correspondsToVariable| V_brownies
    O_kleur -->|correspondsToVariable| V_kleur
