prefix riepr: <https://data.riepr.omgeving.vlaanderen.be/ns/riepr#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix pplan: <http://purl.org/net/p-plan#>
prefix sosa: <http://www.w3.org/ns/sosa/>

CONSTRUCT
{
    ?pr sosa:implementedBy ?val .
}
WHERE
{
    ?pr a riepr:Proces ;
    pplan:hasInputVar ?v .
    ?v a pplan:Variable ;
    rdf:value ?val .
}



