PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
    ?obs sosa:phenomenonTime <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021> ;
         sosa:resultTime "2022-01-01T00:00:00"^^xsd:dateTime .

    <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021>
        a time:Interval ;
        time:hasBeginning <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021/begin> ;
        time:hasEnd       <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021/einde> .

    <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021/begin>
        a time:Instant ;
        time:inXSDDateTime "2021-01-01T00:00:00"^^xsd:dateTime .

    <https://data.riepr.omgeving.vlaanderen.be/id/tijd/jaar/2021/einde>
        a time:Instant ;
        time:inXSDDateTime "2021-12-31T23:59:59"^^xsd:dateTime .
}
WHERE {
    ?obs a sosa:Observation .
}
