services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: riepr
      POSTGRES_PASSWORD: riepr
      POSTGRES_DB: riepr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@vlaanderen.be
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data: