PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class ?property ?range ?label ?comment ?subjectClass ?predicate ?objectClass
WHERE {
    # Klassen vinden - alles wat als type wordt gebruikt
    { ?s a ?class . FILTER(isIRI(?class)) } UNION
    { ?class a owl:Class }
    
    # Filter uit standaard RDF/RDFS klassen
    FILTER(?class NOT IN (rdf:Property, rdfs:Class, rdfs:Resource, owl:Class, owl:Thing))
    
    # Properties van instanties
    OPTIONAL {
        ?instance a ?class .
        ?instance ?property ?value .
        BIND(datatype(?value) as ?range)
    }
    
    # Labels en comments
    OPTIONAL { ?class rdfs:label ?label }
    OPTIONAL { ?class rdfs:comment ?comment }
    
    # Relaties tussen instanties van verschillende klassen
    OPTIONAL {
        ?subj ?pred ?obj .
        ?subj a ?subjectClass .
        ?obj a ?objectClass .
        FILTER(?subjectClass != ?objectClass)
        #FILTER(isIRI(?obj))
        FILTER(?subjectClass NOT IN (rdf:Property, rdfs:Class, rdfs:Resource, owl:Class, owl:Thing))
        FILTER(?objectClass NOT IN (rdf:Property, rdfs:Class, rdfs:Resource, owl:Class, owl:Thing))
        BIND(?pred as ?predicate)
    }

}
ORDER BY ?class ?property