logging:
  level:
    root: WARN
    org.openldes: INFO

orchestrator:
  directory: /ldio/pipelines


spring:
  datasource:
    url: "jdbc:postgresql://postgres-ldio-rdb-out:5432/ldio-rdb-out"
    username: "admin"
    password: "admin"
