springdoc:
  swagger-ui:
    path: /v1/swagger
ldes-server:
  host-name: "http://192.168.1.6:8081"
management:
  tracing:
    enabled:
      false
spring:
  datasource:
    url: 'jdbc:postgresql://ldes-postgres:5432/ldesserver'
    username: admin
    password: admin

